@startuml Basic Mock Arechitecture
allow_mixing
skinparam {
  componentStyle rectangle
  RectangleBackgroundColor #LightBlue
  RoundCorner 10
  FontSize 8
  BorderThickness 0.5
}

component "Test_NotesObjects.bss" as Test_NotesObjects
component "BaliTestRunner.bss" as BaliTestRunner #PaleVioletRed
component "NotesObjects.bss" as NotesObjects #PHYSICAL
component "NotesObjectsRichText.bss" as NotesObjectsRichText #PHYSICAL
component "NotesObjectsStandalone.bss" as NotesObjectsStandalone #PHYSICAL
component "NotesObjectsXML.bss" as NotesObjectsXML #PHYSICAL

Test_NotesObjects --> BaliTestRunner
Test_NotesObjects --> NotesObjects
NotesObjects --> NotesObjectsRichText
NotesObjects --> NotesObjectsStandalone
NotesObjects --> NotesObjectsXML

@enduml